pygments: true
markdown: maruku
exclude: [deploy.sh,.ignore/]

maruku:
  use_tex:    true
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex/

# TODO: Enable this and setup redirects from current *.html URLs
#permalink: pretty
